{
 "title": "view sync statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Delivery Queue Size Over Time (Per Worker)",
   "type": "timeseries",
   "description": "Evolution of the size of the delivery queue for each worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap delivery_queue_size [1m]))\n"
    }
   ]
  },
  {
   "title": " Sent Message Buffer Size Over Time (Per Worker)",
   "type": "timeseries",
   "description": "Evolution of the size of sent message queue for each worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_msg_buffer_size [1m]))\n"
    }
   ]
  },
  {
   "title": "Held Message Buffer Size Over Time (Per Worker)",
   "type": "timeseries",
   "description": "Evolution of the sent message buffer over time per worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap held_msg_buffer_size [1m]))\n"
    }
   ]
  },
  {
   "title": "Ratio of Delivered vs. Sent Messages (Per Worker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap delivered_msg_count [1m]))\n/\n(\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_msg_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_ack_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_retransmit_req_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_retransmit_count [1m]))\n)\n"
    }
   ]
  },
  {
   "title": "Ratio of Drops (All Types) to Total Sent Messages",
   "type": "timeseries",
   "description": "Global Packet Drop rates across network and all packet types",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap dropped_msg_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap dropped_ack_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap dropped_retransmit_req_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap dropped_retransmit_count [1m]))\n)\n/\n(\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_msg_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_ack_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_retransmit_req_count [1m]))\n    +\n    sum by(worker) (rate({label=\"cbcast_logs\", application=\"cbc\"} | json | unwrap sent_retransmit_count [1m]))\n)\n"
    }
   ]
  }
 ]
}